allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/unenv-preset@2.16.2'
  - '@cloudflare/workerd-darwin-64@1.20260921.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260921.1'
  - '@cloudflare/workerd-linux-64@1.20260921.1'
  - '@cloudflare/workerd-linux-arm64@1.20260921.1'
  - '@cloudflare/workerd-windows-64@1.20260921.1'
  - miniflare@5.20260921.0-alpha
  - workerd@1.20260921.1
  - wrangler@4.136.1 || 4.147.0
  - '@ark/schema@0.56.5'
  - '@ark/util@0.56.5'
  - '@better-auth/api-key@1.7.7'
  - '@better-auth/core@1.7.7'
  - '@better-auth/drizzle-adapter@1.7.7'
  - '@better-auth/kysely-adapter@1.7.7'
  - '@better-auth/memory-adapter@1.7.7'
  - '@better-auth/mongo-adapter@1.7.7'
  - '@better-auth/passkey@1.7.7'
  - '@better-auth/prisma-adapter@1.7.7'
  - '@better-auth/telemetry@1.7.7'
  - arkregex@0.0.11
  - arktype@2.2.6
  - better-auth@1.7.7
