/**
 * Magic link email delivery via Cloudflare Email Routing.
 *
 * Uses the `send_email` Worker binding (configured in wrangler.jsonc)
 * to send sign-in/sign-up emails. The binding's builder overload
 * accepts `{ from, to, subject, html, text }` directly — no need for
 * a third-party MIME library.
 *
 *
 * **Summary of local dev behavior:**
 *
 * | Mode | `binding` value | Emails sent? |
 * |------|-----------------|--------------|
 * | `wrangler dev` (no `remote`) | non-null (simulated) | No — logged to console + temp files |
 * | `wrangler dev` + `remote: true` | non-null (real binding) | Yes — real emails delivered |
 * | No binding configured at all | `null` | Falls back to `console.warn` |
 *
 * One caveat from the docs: `remote: true` sends real emails to real recipients, so use test addresses during dev.
 * Binary attachment `ArrayBuffer` values also can't be serialized in the local simulator — not a concern here since the magic link and OTP templates use only strings.
 *
 * **Requirements:**
 * - Email Routing must be enabled on the sender domain (anemoi.systems).
 * - The `SEND_EMAIL` binding must be configured in `wrangler.jsonc`.
 *
 * @see https://developers.cloudflare.com/email-routing/email-workers/send-email-workers/
 */

// ─── Constants ───────────────────────────────────────────────────────────────

const SENDER_NAME = "Anemoi";
const SENDER_EMAIL = "service-noreply+auth@anemoi.systems";

// ─── OTP Email ───────────────────────────────────────────────────────────────

type OtpType =
	| "sign-in"
	| "email-verification"
	| "forget-password"
	| "change-email";

const OTP_SUBJECTS: Record<OtpType, string> = {
	"sign-in": "Your Anemoi sign-in code",
	"email-verification": "Verify your Anemoi email",
	"forget-password": "Your Anemoi password reset code",
	"change-email": "Confirm your new Anemoi email",
};

/**
 * Send an OTP email using the Cloudflare Email Routing binding.
 * Falls back to console in local dev when the binding is unavailable.
 * The binding is passed in by auth.ts's per-request `buildAuth` rather
 * than kept in a module variable -- Workers do run concurrent requests on
 * one isolate, so module state is not request-scoped.
 */
export async function sendVerificationOTPEmail(
	binding: SendEmail | null,
	email: string,
	otp: string,
	type: OtpType,
): Promise<void> {
	if (!binding) {
		console.warn(
			`[OTP] SEND_EMAIL binding not available. Falling back to console.\n` +
				`  To: ${email}\n` +
				`  Type: ${type}\n` +
				`  OTP: ${otp}`,
		);
		return;
	}

	try {
		await binding.send({
			from: { name: SENDER_NAME, email: SENDER_EMAIL },
			to: email,
			subject: OTP_SUBJECTS[type],
			text: getOtpText(otp, type),
			html: getOtpHtml(otp, type),
		});
	} catch (err) {
		console.error(
			`[OTP] Failed to send email to ${email}:`,
			err instanceof Error ? err.message : err,
		);
		throw new Error("Failed to send OTP email. Please try again.");
	}
}

// ─── Magic Link Email ────────────────────────────────────────────────────────

/**
 * Send a magic link email using the Cloudflare Email Routing binding.
 *
 * If the binding is unavailable (e.g. local dev without email routing),
 * falls back to `console.log` so that magic links still work during
 * development.
 *
 * @param binding - This request's `SEND_EMAIL` binding (`null` when unbound)
 * @param email   - Recipient email address
 * @param url     - The magic link verification URL (generated by better-auth)
 */
export async function sendMagicLinkEmail(
	binding: SendEmail | null,
	email: string,
	url: string,
): Promise<void> {
	if (!binding) {
		console.warn(
			`[Magic Link] SEND_EMAIL binding not available. Falling back to console.\n` +
				`  To: ${email}\n` +
				`  URL: ${url}`,
		);
		return;
	}

	try {
		await binding.send({
			from: { name: SENDER_NAME, email: SENDER_EMAIL },
			to: email,
			subject: "Sign in to Anemoi",
			text: getMagicLinkText(url),
			html: getMagicLinkHtml(url),
		});
	} catch (err) {
		console.error(
			`[Magic Link] Failed to send email to ${email}:`,
			err instanceof Error ? err.message : err,
		);
		// Re-throw so better-auth can surface the error to the client
		throw new Error("Failed to send magic link email. Please try again.");
	}
}

// ─── Email Templates ─────────────────────────────────────────────────────────

/**
 * Plain-text fallback for the magic link email.
 */
function getMagicLinkText(url: string): string {
	return [
		"Sign in to Anemoi",
		"",
		"Click the link below to sign in. This link expires in 5 minutes.",
		"",
		url,
		"",
		"If you didn't request this email, you can safely ignore it.",
		"",
		"— Anemoi",
	].join("\n");
}

/**
 * HTML version of the magic link email.
 *
 * Minimal, inline-styled HTML that renders well across email clients.
 */
function getMagicLinkHtml(url: string): string {
	return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f5;padding:40px 20px;">
    <tr>
      <td align="center">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
          <!-- Header -->
          <tr>
            <td style="padding:32px 32px 0;text-align:center;">
              <h1 style="margin:0;font-size:20px;font-weight:600;color:#18181b;">Anemoi</h1>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:24px 32px;">
              <p style="margin:0 0 16px;font-size:15px;line-height:1.6;color:#3f3f46;">
                Click the button below to sign in. This link expires in <strong>5 minutes</strong>.
              </p>
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center" style="padding:8px 0 24px;">
                    <a href="${url}" target="_blank" style="display:inline-block;padding:12px 32px;background-color:#18181b;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;border-radius:8px;">
                      Sign in
                    </a>
                  </td>
                </tr>
              </table>
              <p style="margin:0 0 8px;font-size:13px;line-height:1.5;color:#71717a;">
                Or copy and paste this URL into your browser:
              </p>
              <p style="margin:0;font-size:12px;line-height:1.5;color:#a1a1aa;word-break:break-all;">
                ${url}
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:16px 32px 32px;border-top:1px solid #f4f4f5;">
              <p style="margin:0;font-size:12px;line-height:1.5;color:#a1a1aa;text-align:center;">
                If you didn't request this email, you can safely ignore it.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

// ─── OTP Templates ───────────────────────────────────────────────────────────

const OTP_BODY_COPY: Record<OtpType, string> = {
	"sign-in":
		"Use the code below to sign in. It expires in <strong>10 minutes</strong>.",
	"email-verification": "Use the code below to verify your email address.",
	"forget-password":
		"Use the code below to reset your password. It expires in <strong>10 minutes</strong>.",
	"change-email": "Use the code below to confirm your new email address.",
};

function getOtpText(otp: string, type: OtpType): string {
	return [
		OTP_SUBJECTS[type],
		"",
		OTP_BODY_COPY[type].replace(/<[^>]+>/g, ""),
		"",
		`Your code: ${otp}`,
		"",
		"If you didn't request this email, you can safely ignore it.",
		"",
		"— Anemoi",
	].join("\n");
}

function getOtpHtml(otp: string, type: OtpType): string {
	return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f5;padding:40px 20px;">
    <tr>
      <td align="center">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
          <tr>
            <td style="padding:32px 32px 0;text-align:center;">
              <h1 style="margin:0;font-size:20px;font-weight:600;color:#18181b;">Anemoi</h1>
            </td>
          </tr>
          <tr>
            <td style="padding:24px 32px;">
              <p style="margin:0 0 24px;font-size:15px;line-height:1.6;color:#3f3f46;">
                ${OTP_BODY_COPY[type]}
              </p>
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center" style="padding:8px 0 24px;">
                    <div style="display:inline-block;padding:16px 40px;background-color:#f4f4f5;border-radius:8px;font-size:32px;font-weight:700;letter-spacing:8px;color:#18181b;font-family:monospace;">
                      ${otp}
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td style="padding:16px 32px 32px;border-top:1px solid #f4f4f5;">
              <p style="margin:0;font-size:12px;line-height:1.5;color:#a1a1aa;text-align:center;">
                If you didn't request this email, you can safely ignore it.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}
