// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
//
// `worker-configuration.d.ts` (generated by `wrangler types`, not part of
// `.svelte-kit/tsconfig.json`'s own `include` list) declares the ambient
// `Env`/`D1Database`/`SendEmail` types every server file in src/ relies
// on -- referencing it here pulls it into the program since app.d.ts
// itself is already included.
/// <reference path="../worker-configuration.d.ts" />
import type { UserIdentity } from "$lib/user.context.svelte";

declare global {
	namespace App {
		// interface Error {}
		interface Locals {
			/** Populated in `hooks.server.ts` from the request's session
			 * cookie or API key (`auth-utils.ts`'s `buildSessionHeaders`). */
			session: { id: string; userId: string; expiresAt: Date } | null;
			user: UserIdentity | null;
			/** Short per-request id, set in hooks.server.ts, so staged
			 * diagnostic logs from the same request (hooks.server.ts,
			 * routes/auth/logout/+server.ts) can be
			 * correlated in `wrangler tail` output when several auth
			 * requests are in flight on the same isolate at once -- added
			 * to chase an intermittent production hang (#171 follow-up)
			 * that never reproduced locally. */
			requestId: string;
		}
		// interface PageData {}
		// interface PageState {}
		interface Platform {
			/** Cloudflare Worker bindings -- see console/wrangler.jsonc and
			 * the generated console/worker-configuration.d.ts (`Env`), plus
			 * `INTERNAL_PROXY_SECRET` (#171): a `wrangler secret put` value,
			 * not a wrangler.jsonc binding, so `wrangler types` has no way to
			 * know it exists -- same hand-extension pattern as
			 * docker/api/src/index.ts's `RealApiEnv`. Shared with
			 * anemoi-api-real; see routes/api/[...path]/+server.ts. */
			env: Env & { INTERNAL_PROXY_SECRET: string };
			/** Lets auth.ts hand better-auth's background work to
			 * `waitUntil` (`advanced.backgroundTasks`). */
			ctx: ExecutionContext;
		}
	}
}

export {};
